### PR TITLE
Modified extension

### PR DESCRIPTION
**Pull request by dinesh1101**

### CODE REVIEW

**Comment by dinesh1101** [comment]
@tamilarasumk731

**Comment by tamilarasumk731** [comment]
@dinesh1101 Can you explain the changes that you made?

**Comment by AkbarHabeeb** [comment]
@dinesh1101 Did you changed the color alone? Can you call us tomorrow.

**Comment by dinesh1101** [comment]
@tamilarasumk731 
@AkbarHabeeb 
check my new commit

**Comment by AkbarHabeeb** [comment]
@dinesh1101 Testing now

**Comment by AkbarHabeeb** [comment]
@dinesh1101 Nice. 
1. The logo was quality was so bad, change the quality alone Dinesh. We can start with our next works.

**Pull request merged**
